// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dric.proto

package dric.proto;

/**
 * Protobuf type {@code dric.proto.BoundingBoxProto}
 */
public  final class BoundingBoxProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dric.proto.BoundingBoxProto)
    BoundingBoxProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BoundingBoxProto.newBuilder() to construct.
  private BoundingBoxProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BoundingBoxProto() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BoundingBoxProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BoundingBoxProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            dric.proto.ImageCoordinateProto.Builder subBuilder = null;
            if (tl_ != null) {
              subBuilder = tl_.toBuilder();
            }
            tl_ = input.readMessage(dric.proto.ImageCoordinateProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(tl_);
              tl_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            dric.proto.ImageCoordinateProto.Builder subBuilder = null;
            if (br_ != null) {
              subBuilder = br_.toBuilder();
            }
            br_ = input.readMessage(dric.proto.ImageCoordinateProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(br_);
              br_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dric.proto.Dric.internal_static_dric_proto_BoundingBoxProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dric.proto.Dric.internal_static_dric_proto_BoundingBoxProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dric.proto.BoundingBoxProto.class, dric.proto.BoundingBoxProto.Builder.class);
  }

  public static final int TL_FIELD_NUMBER = 1;
  private dric.proto.ImageCoordinateProto tl_;
  /**
   * <code>.dric.proto.ImageCoordinateProto tl = 1;</code>
   */
  public boolean hasTl() {
    return tl_ != null;
  }
  /**
   * <code>.dric.proto.ImageCoordinateProto tl = 1;</code>
   */
  public dric.proto.ImageCoordinateProto getTl() {
    return tl_ == null ? dric.proto.ImageCoordinateProto.getDefaultInstance() : tl_;
  }
  /**
   * <code>.dric.proto.ImageCoordinateProto tl = 1;</code>
   */
  public dric.proto.ImageCoordinateProtoOrBuilder getTlOrBuilder() {
    return getTl();
  }

  public static final int BR_FIELD_NUMBER = 2;
  private dric.proto.ImageCoordinateProto br_;
  /**
   * <code>.dric.proto.ImageCoordinateProto br = 2;</code>
   */
  public boolean hasBr() {
    return br_ != null;
  }
  /**
   * <code>.dric.proto.ImageCoordinateProto br = 2;</code>
   */
  public dric.proto.ImageCoordinateProto getBr() {
    return br_ == null ? dric.proto.ImageCoordinateProto.getDefaultInstance() : br_;
  }
  /**
   * <code>.dric.proto.ImageCoordinateProto br = 2;</code>
   */
  public dric.proto.ImageCoordinateProtoOrBuilder getBrOrBuilder() {
    return getBr();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (tl_ != null) {
      output.writeMessage(1, getTl());
    }
    if (br_ != null) {
      output.writeMessage(2, getBr());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (tl_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTl());
    }
    if (br_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getBr());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dric.proto.BoundingBoxProto)) {
      return super.equals(obj);
    }
    dric.proto.BoundingBoxProto other = (dric.proto.BoundingBoxProto) obj;

    if (hasTl() != other.hasTl()) return false;
    if (hasTl()) {
      if (!getTl()
          .equals(other.getTl())) return false;
    }
    if (hasBr() != other.hasBr()) return false;
    if (hasBr()) {
      if (!getBr()
          .equals(other.getBr())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTl()) {
      hash = (37 * hash) + TL_FIELD_NUMBER;
      hash = (53 * hash) + getTl().hashCode();
    }
    if (hasBr()) {
      hash = (37 * hash) + BR_FIELD_NUMBER;
      hash = (53 * hash) + getBr().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dric.proto.BoundingBoxProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dric.proto.BoundingBoxProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dric.proto.BoundingBoxProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dric.proto.BoundingBoxProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dric.proto.BoundingBoxProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dric.proto.BoundingBoxProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dric.proto.BoundingBoxProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dric.proto.BoundingBoxProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dric.proto.BoundingBoxProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dric.proto.BoundingBoxProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dric.proto.BoundingBoxProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dric.proto.BoundingBoxProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dric.proto.BoundingBoxProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dric.proto.BoundingBoxProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dric.proto.BoundingBoxProto)
      dric.proto.BoundingBoxProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dric.proto.Dric.internal_static_dric_proto_BoundingBoxProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dric.proto.Dric.internal_static_dric_proto_BoundingBoxProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dric.proto.BoundingBoxProto.class, dric.proto.BoundingBoxProto.Builder.class);
    }

    // Construct using dric.proto.BoundingBoxProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (tlBuilder_ == null) {
        tl_ = null;
      } else {
        tl_ = null;
        tlBuilder_ = null;
      }
      if (brBuilder_ == null) {
        br_ = null;
      } else {
        br_ = null;
        brBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dric.proto.Dric.internal_static_dric_proto_BoundingBoxProto_descriptor;
    }

    @java.lang.Override
    public dric.proto.BoundingBoxProto getDefaultInstanceForType() {
      return dric.proto.BoundingBoxProto.getDefaultInstance();
    }

    @java.lang.Override
    public dric.proto.BoundingBoxProto build() {
      dric.proto.BoundingBoxProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dric.proto.BoundingBoxProto buildPartial() {
      dric.proto.BoundingBoxProto result = new dric.proto.BoundingBoxProto(this);
      if (tlBuilder_ == null) {
        result.tl_ = tl_;
      } else {
        result.tl_ = tlBuilder_.build();
      }
      if (brBuilder_ == null) {
        result.br_ = br_;
      } else {
        result.br_ = brBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dric.proto.BoundingBoxProto) {
        return mergeFrom((dric.proto.BoundingBoxProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dric.proto.BoundingBoxProto other) {
      if (other == dric.proto.BoundingBoxProto.getDefaultInstance()) return this;
      if (other.hasTl()) {
        mergeTl(other.getTl());
      }
      if (other.hasBr()) {
        mergeBr(other.getBr());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dric.proto.BoundingBoxProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dric.proto.BoundingBoxProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private dric.proto.ImageCoordinateProto tl_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dric.proto.ImageCoordinateProto, dric.proto.ImageCoordinateProto.Builder, dric.proto.ImageCoordinateProtoOrBuilder> tlBuilder_;
    /**
     * <code>.dric.proto.ImageCoordinateProto tl = 1;</code>
     */
    public boolean hasTl() {
      return tlBuilder_ != null || tl_ != null;
    }
    /**
     * <code>.dric.proto.ImageCoordinateProto tl = 1;</code>
     */
    public dric.proto.ImageCoordinateProto getTl() {
      if (tlBuilder_ == null) {
        return tl_ == null ? dric.proto.ImageCoordinateProto.getDefaultInstance() : tl_;
      } else {
        return tlBuilder_.getMessage();
      }
    }
    /**
     * <code>.dric.proto.ImageCoordinateProto tl = 1;</code>
     */
    public Builder setTl(dric.proto.ImageCoordinateProto value) {
      if (tlBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tl_ = value;
        onChanged();
      } else {
        tlBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.dric.proto.ImageCoordinateProto tl = 1;</code>
     */
    public Builder setTl(
        dric.proto.ImageCoordinateProto.Builder builderForValue) {
      if (tlBuilder_ == null) {
        tl_ = builderForValue.build();
        onChanged();
      } else {
        tlBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.dric.proto.ImageCoordinateProto tl = 1;</code>
     */
    public Builder mergeTl(dric.proto.ImageCoordinateProto value) {
      if (tlBuilder_ == null) {
        if (tl_ != null) {
          tl_ =
            dric.proto.ImageCoordinateProto.newBuilder(tl_).mergeFrom(value).buildPartial();
        } else {
          tl_ = value;
        }
        onChanged();
      } else {
        tlBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.dric.proto.ImageCoordinateProto tl = 1;</code>
     */
    public Builder clearTl() {
      if (tlBuilder_ == null) {
        tl_ = null;
        onChanged();
      } else {
        tl_ = null;
        tlBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.dric.proto.ImageCoordinateProto tl = 1;</code>
     */
    public dric.proto.ImageCoordinateProto.Builder getTlBuilder() {
      
      onChanged();
      return getTlFieldBuilder().getBuilder();
    }
    /**
     * <code>.dric.proto.ImageCoordinateProto tl = 1;</code>
     */
    public dric.proto.ImageCoordinateProtoOrBuilder getTlOrBuilder() {
      if (tlBuilder_ != null) {
        return tlBuilder_.getMessageOrBuilder();
      } else {
        return tl_ == null ?
            dric.proto.ImageCoordinateProto.getDefaultInstance() : tl_;
      }
    }
    /**
     * <code>.dric.proto.ImageCoordinateProto tl = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dric.proto.ImageCoordinateProto, dric.proto.ImageCoordinateProto.Builder, dric.proto.ImageCoordinateProtoOrBuilder> 
        getTlFieldBuilder() {
      if (tlBuilder_ == null) {
        tlBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dric.proto.ImageCoordinateProto, dric.proto.ImageCoordinateProto.Builder, dric.proto.ImageCoordinateProtoOrBuilder>(
                getTl(),
                getParentForChildren(),
                isClean());
        tl_ = null;
      }
      return tlBuilder_;
    }

    private dric.proto.ImageCoordinateProto br_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dric.proto.ImageCoordinateProto, dric.proto.ImageCoordinateProto.Builder, dric.proto.ImageCoordinateProtoOrBuilder> brBuilder_;
    /**
     * <code>.dric.proto.ImageCoordinateProto br = 2;</code>
     */
    public boolean hasBr() {
      return brBuilder_ != null || br_ != null;
    }
    /**
     * <code>.dric.proto.ImageCoordinateProto br = 2;</code>
     */
    public dric.proto.ImageCoordinateProto getBr() {
      if (brBuilder_ == null) {
        return br_ == null ? dric.proto.ImageCoordinateProto.getDefaultInstance() : br_;
      } else {
        return brBuilder_.getMessage();
      }
    }
    /**
     * <code>.dric.proto.ImageCoordinateProto br = 2;</code>
     */
    public Builder setBr(dric.proto.ImageCoordinateProto value) {
      if (brBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        br_ = value;
        onChanged();
      } else {
        brBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.dric.proto.ImageCoordinateProto br = 2;</code>
     */
    public Builder setBr(
        dric.proto.ImageCoordinateProto.Builder builderForValue) {
      if (brBuilder_ == null) {
        br_ = builderForValue.build();
        onChanged();
      } else {
        brBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.dric.proto.ImageCoordinateProto br = 2;</code>
     */
    public Builder mergeBr(dric.proto.ImageCoordinateProto value) {
      if (brBuilder_ == null) {
        if (br_ != null) {
          br_ =
            dric.proto.ImageCoordinateProto.newBuilder(br_).mergeFrom(value).buildPartial();
        } else {
          br_ = value;
        }
        onChanged();
      } else {
        brBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.dric.proto.ImageCoordinateProto br = 2;</code>
     */
    public Builder clearBr() {
      if (brBuilder_ == null) {
        br_ = null;
        onChanged();
      } else {
        br_ = null;
        brBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.dric.proto.ImageCoordinateProto br = 2;</code>
     */
    public dric.proto.ImageCoordinateProto.Builder getBrBuilder() {
      
      onChanged();
      return getBrFieldBuilder().getBuilder();
    }
    /**
     * <code>.dric.proto.ImageCoordinateProto br = 2;</code>
     */
    public dric.proto.ImageCoordinateProtoOrBuilder getBrOrBuilder() {
      if (brBuilder_ != null) {
        return brBuilder_.getMessageOrBuilder();
      } else {
        return br_ == null ?
            dric.proto.ImageCoordinateProto.getDefaultInstance() : br_;
      }
    }
    /**
     * <code>.dric.proto.ImageCoordinateProto br = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dric.proto.ImageCoordinateProto, dric.proto.ImageCoordinateProto.Builder, dric.proto.ImageCoordinateProtoOrBuilder> 
        getBrFieldBuilder() {
      if (brBuilder_ == null) {
        brBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dric.proto.ImageCoordinateProto, dric.proto.ImageCoordinateProto.Builder, dric.proto.ImageCoordinateProtoOrBuilder>(
                getBr(),
                getParentForChildren(),
                isClean());
        br_ = null;
      }
      return brBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dric.proto.BoundingBoxProto)
  }

  // @@protoc_insertion_point(class_scope:dric.proto.BoundingBoxProto)
  private static final dric.proto.BoundingBoxProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dric.proto.BoundingBoxProto();
  }

  public static dric.proto.BoundingBoxProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BoundingBoxProto>
      PARSER = new com.google.protobuf.AbstractParser<BoundingBoxProto>() {
    @java.lang.Override
    public BoundingBoxProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BoundingBoxProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BoundingBoxProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BoundingBoxProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dric.proto.BoundingBoxProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

