// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dric.proto

package dric.proto;

public interface BoundingBoxProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dric.proto.BoundingBoxProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.dric.proto.ImageCoordinateProto tl = 1;</code>
   */
  boolean hasTl();
  /**
   * <code>.dric.proto.ImageCoordinateProto tl = 1;</code>
   */
  dric.proto.ImageCoordinateProto getTl();
  /**
   * <code>.dric.proto.ImageCoordinateProto tl = 1;</code>
   */
  dric.proto.ImageCoordinateProtoOrBuilder getTlOrBuilder();

  /**
   * <code>.dric.proto.ImageCoordinateProto br = 2;</code>
   */
  boolean hasBr();
  /**
   * <code>.dric.proto.ImageCoordinateProto br = 2;</code>
   */
  dric.proto.ImageCoordinateProto getBr();
  /**
   * <code>.dric.proto.ImageCoordinateProto br = 2;</code>
   */
  dric.proto.ImageCoordinateProtoOrBuilder getBrOrBuilder();
}
