// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dric.proto

package dric.proto;

public interface CameraFrameResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dric.proto.CameraFrameResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.dric.proto.CameraFrameProto frame = 1;</code>
   */
  boolean hasFrame();
  /**
   * <code>.dric.proto.CameraFrameProto frame = 1;</code>
   */
  dric.proto.CameraFrameProto getFrame();
  /**
   * <code>.dric.proto.CameraFrameProto frame = 1;</code>
   */
  dric.proto.CameraFrameProtoOrBuilder getFrameOrBuilder();

  /**
   * <code>.marmot.proto.ErrorProto error = 2;</code>
   */
  boolean hasError();
  /**
   * <code>.marmot.proto.ErrorProto error = 2;</code>
   */
  marmot.proto.ErrorProto getError();
  /**
   * <code>.marmot.proto.ErrorProto error = 2;</code>
   */
  marmot.proto.ErrorProtoOrBuilder getErrorOrBuilder();

  public dric.proto.CameraFrameResponse.EitherCase getEitherCase();
}
