// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dric.proto

package dric.proto;

public interface EndPointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dric.proto.EndPoint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string host = 1;</code>
   */
  java.lang.String getHost();
  /**
   * <code>string host = 1;</code>
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>int32 port = 2;</code>
   */
  int getPort();
}
