// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dric.proto

package dric.proto;

public interface ImageCoordinateProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dric.proto.ImageCoordinateProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 x = 1;</code>
   */
  int getX();

  /**
   * <code>int32 y = 2;</code>
   */
  int getY();
}
