// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dric.proto

package dric.proto;

public interface ObjectBBoxTrackProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dric.proto.ObjectBBoxTrackProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 영상을 취득한 카메라 식별자
   * </pre>
   *
   * <code>string camera_id = 1;</code>
   */
  java.lang.String getCameraId();
  /**
   * <pre>
   * 영상을 취득한 카메라 식별자
   * </pre>
   *
   * <code>string camera_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCameraIdBytes();

  /**
   * <pre>
   * 인지된 객체의 식별자
   * </pre>
   *
   * <code>string luid = 2;</code>
   */
  java.lang.String getLuid();
  /**
   * <pre>
   * 인지된 객체의 식별자
   * </pre>
   *
   * <code>string luid = 2;</code>
   */
  com.google.protobuf.ByteString
      getLuidBytes();

  /**
   * <pre>
   * 인지된 객체의 종류
   * </pre>
   *
   * <code>string object_class = 3;</code>
   */
  java.lang.String getObjectClass();
  /**
   * <pre>
   * 인지된 객체의 종류
   * </pre>
   *
   * <code>string object_class = 3;</code>
   */
  com.google.protobuf.ByteString
      getObjectClassBytes();

  /**
   * <pre>
   * 인지된 객체의 영상 내 영역
   * </pre>
   *
   * <code>.dric.proto.BoundingBoxProto bbox = 4;</code>
   */
  boolean hasBbox();
  /**
   * <pre>
   * 인지된 객체의 영상 내 영역
   * </pre>
   *
   * <code>.dric.proto.BoundingBoxProto bbox = 4;</code>
   */
  dric.proto.BoundingBoxProto getBbox();
  /**
   * <pre>
   * 인지된 객체의 영상 내 영역
   * </pre>
   *
   * <code>.dric.proto.BoundingBoxProto bbox = 4;</code>
   */
  dric.proto.BoundingBoxProtoOrBuilder getBboxOrBuilder();

  /**
   * <pre>
   * 인지된 객체의 방향
   * </pre>
   *
   * <code>float heading = 5;</code>
   */
  float getHeading();

  /**
   * <pre>
   * 이미지 취득 시각
   * </pre>
   *
   * <code>int64 ts = 6;</code>
   */
  long getTs();
}
