// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dric.proto

package dric.proto;

public interface RotationProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dric.proto.RotationProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double yaw = 1;</code>
   */
  double getYaw();

  /**
   * <code>double pitch = 2;</code>
   */
  double getPitch();

  /**
   * <code>double roll = 3;</code>
   */
  double getRoll();
}
