// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dric.proto

package dric.proto;

public interface CameraFrameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dric.proto.CameraFrameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string camera_id = 1;</code>
   */
  java.lang.String getCameraId();
  /**
   * <code>string camera_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCameraIdBytes();

  /**
   * <code>int64 ts = 2;</code>
   */
  long getTs();
}
