// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dric.proto

package dric.proto;

public interface CameraFrameProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dric.proto.CameraFrameProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 영상을 취득한 카메라 식별자
   * </pre>
   *
   * <code>string camera_id = 1;</code>
   */
  java.lang.String getCameraId();
  /**
   * <pre>
   * 영상을 취득한 카메라 식별자
   * </pre>
   *
   * <code>string camera_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCameraIdBytes();

  /**
   * <pre>
   * 영상 데이터
   * </pre>
   *
   * <code>bytes image = 2;</code>
   */
  com.google.protobuf.ByteString getImage();

  /**
   * <pre>
   * 이미지 취득 시각
   * </pre>
   *
   * <code>int64 ts = 3;</code>
   */
  long getTs();
}
