// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dric.proto

package dric.proto;

public interface CameraInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dric.proto.CameraInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string rtsp_url = 2;</code>
   */
  java.lang.String getRtspUrl();
  /**
   * <code>string rtsp_url = 2;</code>
   */
  com.google.protobuf.ByteString
      getRtspUrlBytes();
}
