// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dric.proto

package dric.proto;

public interface CameraFrameRangeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dric.proto.CameraFrameRangeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * target camera id
   * </pre>
   *
   * <code>string camera_id = 1;</code>
   */
  java.lang.String getCameraId();
  /**
   * <pre>
   * target camera id
   * </pre>
   *
   * <code>string camera_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCameraIdBytes();

  /**
   * <pre>
   * timestamp of the start frame
   * </pre>
   *
   * <code>int64 start_ts = 2;</code>
   */
  long getStartTs();

  /**
   * <pre>
   * timestamp of the last frame
   * </pre>
   *
   * <code>int64 stop_ts = 3;</code>
   */
  long getStopTs();
}
