// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dric.proto

package dric.proto;

public interface EndPointResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dric.proto.EndPointResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.dric.proto.EndPoint end_point = 1;</code>
   */
  boolean hasEndPoint();
  /**
   * <code>.dric.proto.EndPoint end_point = 1;</code>
   */
  dric.proto.EndPoint getEndPoint();
  /**
   * <code>.dric.proto.EndPoint end_point = 1;</code>
   */
  dric.proto.EndPointOrBuilder getEndPointOrBuilder();

  /**
   * <code>.marmot.proto.ErrorProto error = 2;</code>
   */
  boolean hasError();
  /**
   * <code>.marmot.proto.ErrorProto error = 2;</code>
   */
  marmot.proto.ErrorProto getError();
  /**
   * <code>.marmot.proto.ErrorProto error = 2;</code>
   */
  marmot.proto.ErrorProtoOrBuilder getErrorOrBuilder();

  public dric.proto.EndPointResponse.EitherCase getEitherCase();
}
