// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dric.proto

package dric.proto;

public interface JdbcEndPointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dric.proto.JdbcEndPoint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string system = 1;</code>
   */
  java.lang.String getSystem();
  /**
   * <code>string system = 1;</code>
   */
  com.google.protobuf.ByteString
      getSystemBytes();

  /**
   * <code>string host = 2;</code>
   */
  java.lang.String getHost();
  /**
   * <code>string host = 2;</code>
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>int32 port = 3;</code>
   */
  int getPort();

  /**
   * <code>string db_name = 4;</code>
   */
  java.lang.String getDbName();
  /**
   * <code>string db_name = 4;</code>
   */
  com.google.protobuf.ByteString
      getDbNameBytes();

  /**
   * <code>string user = 5;</code>
   */
  java.lang.String getUser();
  /**
   * <code>string user = 5;</code>
   */
  com.google.protobuf.ByteString
      getUserBytes();

  /**
   * <code>string password = 6;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 6;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
