// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dric.proto

package dric.proto;

public interface ObjectTrackProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dric.proto.ObjectTrackProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 영상을 취득한 카메라 식별자
   * </pre>
   *
   * <code>string camera_id = 1;</code>
   */
  java.lang.String getCameraId();
  /**
   * <pre>
   * 영상을 취득한 카메라 식별자
   * </pre>
   *
   * <code>string camera_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCameraIdBytes();

  /**
   * <pre>
   * 인지된 객체의 식별자
   * </pre>
   *
   * <code>string luid = 2;</code>
   */
  java.lang.String getLuid();
  /**
   * <pre>
   * 인지된 객체의 식별자
   * </pre>
   *
   * <code>string luid = 2;</code>
   */
  com.google.protobuf.ByteString
      getLuidBytes();

  /**
   * <pre>
   * 인지된 객체의 종류
   * </pre>
   *
   * <code>string object_class = 3;</code>
   */
  java.lang.String getObjectClass();
  /**
   * <pre>
   * 인지된 객체의 종류
   * </pre>
   *
   * <code>string object_class = 3;</code>
   */
  com.google.protobuf.ByteString
      getObjectClassBytes();

  /**
   * <pre>
   * 위경도 좌표계
   * </pre>
   *
   * <code>.dric.proto.CoordinateProto coordinate = 4;</code>
   */
  boolean hasCoordinate();
  /**
   * <pre>
   * 위경도 좌표계
   * </pre>
   *
   * <code>.dric.proto.CoordinateProto coordinate = 4;</code>
   */
  dric.proto.CoordinateProto getCoordinate();
  /**
   * <pre>
   * 위경도 좌표계
   * </pre>
   *
   * <code>.dric.proto.CoordinateProto coordinate = 4;</code>
   */
  dric.proto.CoordinateProtoOrBuilder getCoordinateOrBuilder();

  /**
   * <pre>
   * 방위각
   * </pre>
   *
   * <code>float azimuth = 5;</code>
   */
  float getAzimuth();

  /**
   * <pre>
   * 이미지 취득 시각
   * </pre>
   *
   * <code>int64 ts = 6;</code>
   */
  long getTs();
}
