// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dric.proto

package dric.proto;

public interface PlaybackStreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dric.proto.PlaybackStreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string camera_id = 1;</code>
   */
  java.lang.String getCameraId();
  /**
   * <code>string camera_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCameraIdBytes();

  /**
   * <code>string start_time = 2;</code>
   */
  java.lang.String getStartTime();
  /**
   * <code>string start_time = 2;</code>
   */
  com.google.protobuf.ByteString
      getStartTimeBytes();

  /**
   * <code>string stop_time = 3;</code>
   */
  java.lang.String getStopTime();
  /**
   * <code>string stop_time = 3;</code>
   */
  com.google.protobuf.ByteString
      getStopTimeBytes();
}
