// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dric.proto

package dric.proto;

public interface VideoStreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dric.proto.VideoStream)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string camera_id = 1;</code>
   */
  java.lang.String getCameraId();
  /**
   * <code>string camera_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCameraIdBytes();

  /**
   * <code>string rtsp_url = 2;</code>
   */
  java.lang.String getRtspUrl();
  /**
   * <code>string rtsp_url = 2;</code>
   */
  com.google.protobuf.ByteString
      getRtspUrlBytes();
}
